---
name: sola MPD addon
version: 0.0.1
slug: sola-mpd
description: mpd web client 
url: https://github.com/bram.diederik/hassio-addons/tree/master/sola_mod/
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
webui: http://[HOST]:[PORT:3000]
ingress: true
init: false
panel_icon: mdi:web-box
options:
ports:
  30000/tcp: 3000
ports_description:
  3000/tcp: Web interface http
