---
name: "Dependabot Automerge - Action"

on:
  pull_request:

jobs:
  worker:
    runs-on: ubuntu-latest

    if: github.actor == 'dependabot[bot]'
    steps:
      #- name: Wait for CI/CT/CD to succeed
      #  uses: fountainhead/action-wait-for-check@v1.0.0
      #  id: wait-for-build
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    checkName: Tests + Deploy Docker Image - DEV
      #    ref: ${{ github.event.pull_request.head.sha || github.sha }}

      #- name: Wait for CI/CT/CD to succeed pt2
      #  uses: fountainhead/action-wait-for-check@v1.0.0
      #  id: wait-for-ci
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    checkName: MegaLinter
      #    ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: automerge
        uses: actions/github-script@v6
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}