---
name: Automatically bump version on addon base updates

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Update ghcr.io/hassio-addons/base-python') }} # Detect that the base addon has been updated
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: "true"
          fetch-depth: 0
      - name: "Retrieve version & increment it"
        id: version
        run: |
          configFiles=$(find . -name 'config.yaml' -print0 | xargs -r0 echo)
          for configfile in $configFiles; do
              OLD_VERSION=$(cat $configfile | grep 'version: ' | head -1 | sed s/"version: "//)
              NEW_VERSION=$(echo $OLD_VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
              sed -i "s/$OLD_VERSION/$NEW_VERSION/g" $configfile
              echo "Incremented addon $configfile from version $OLD_VERSION to $NEW_VERSION"
          done
      - name: "Update Changelog"
        id: changelog
        run: |
          repo_url="https://api.github.com/repos/hassio-addons/addon-base"
          response=$(curl -s "$repo_url/releases")
          latest_version=$(echo "$response" | grep -oP '"tag_name": "\K[^"]+' | head -n1)
          find . -name "CHANGELOG.md" -exec grep -l "# Changelog" {} \; | while read -r file; do
            new_version=$(grep -oP '(?<=## )\d+\.\d+\.\d+' $file | sort -rV | head -n1 | awk -F. '{$NF+=1; OFS="."; print $0}' )
            major=$(echo "$new_version" | cut -d '.' -f 1)
            minor=$(echo "$new_version" | cut -d '.' -f 2)
            patch=$(echo "$new_version" | cut -d '.' -f 3)
            ((patch++))
            new_version="$major.$minor.$patch"

            sed -i '/# Changelog/a \ ' "$file"
            sed -i "/# Changelog/a \\## $new_version \n - automatically update hassio-addon-base to version $latest_version" "$file"
            echo "Added changelog auto text for $file and base version $latest_version"
          done
      - name: Commit & Push
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: "Increment addon version due to addon base update"
