---
name: Automatically bump version on addon base updates

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Update ghcr.io/hassio-addons/base') }} # Detect that the base addon has been updated
    steps:
      - name: "Retrieve version & increment it"
        id: version
        run: |
          for configfile in */*config.yaml; do
              OLD_VERSION=$(cat $configfile | grep 'version: ' | head -1 | sed s/"version: "//)
              NEW_VERSION=$(echo $OLD_VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
              sed -i "s/$OLD_VERSION/$NEW_VERSION/g" $configfile
              echo "Incremented addon $configfile from version $OLD_VERSION to $NEW_VERSION"
          done
      - name: Commit & Push
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Increment addon version due to addon base update"
